### ISSUE TITLE
HTTP 403 - /espace-client?type-front=WEB_ORDINATEUR

### ISSUE THREAD

**Issue by The-MasterChief** [Jezza34000/veolia-api#2]
Hello,

I would like to use your package to retrieve my consumption data from Veolia but I am having an issue retrieving my account information.

```
DEBUG:VeoliaAPI:Requesting access token...
DEBUG:VeoliaAPI:OK - Access token retrieved
DEBUG:VeoliaAPI:Getting user & billing data...
Traceback (most recent call last):
  File "/root/okveolia.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/okveolia.py", line 17, in main
    await api.fetch_all_data(2024, 11)
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 519, in fetch_all_data
    self.account_data.monthly_consumption = await self.get_consumption_data(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 370, in get_consumption_data
    await self.check_token()
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 266, in check_token
    await self.login()
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 243, in login
    await self.get_client_data()
  File "/usr/local/lib/python3.12/site-packages/veolia_api/veolia_api.py", line 306, in get_client_data
    raise VeoliaAPIGetDataError(
veolia_api.exceptions.VeoliaAPIGetDataError: call to= espace-client failed with http status= 403
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff1e465b080>
ERROR:asyncio:Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x7ff1e3f6aab0>, 523385.811021384)])', 'deque([(<aiohttp.client_proto.ResponseHandler object at 0x7ff1e3f6a9f0>, 523385.931586175)])', 'deque([(<aiohttp.client_proto.ResponseHandler object at 0x7ff1e3f6b170>, 523386.00854948)])']
connector: <aiohttp.connector.TCPConnector object at 0x7ff1e4381f10>
```
There seems to be a 403 http error for the following aiohttp request :

https://prd-ael-sirius-backend.istefr.fr/espace-client?type-front=WEB_ORDINATEUR

Everything seems ok in your code and I don't understand what's causing the issue.
Any idea?

**Comment by Jezza34000** [comment]
Hi,
Where are you living ?
Country / City ?

**Comment by thanaus** [comment]
Hello,

I live outside France but it's for a friend.
The city code is 06330 and I can connect with the website https://login.eau.veolia.fr/

**Comment by The-MasterChief** [comment]
Hello,

I live outside France but it's for a friend.
The city code is 06330 and I can connect with the website https://login.eau.veolia.fr/

**Comment by Jezza34000** [comment]
Can you take a screenshot of the main page when you are logged in eau.veolia.fr ?

**Comment by The-MasterChief** [comment]
This is the screenshot of the main page :

![image](https://github.com/user-attachments/assets/b2125e9c-bd6a-4f39-8259-65edba8e1871)

**Comment by Jezza34000** [comment]
After logged in with you credentials please

**Comment by The-MasterChief** [comment]
Voici la capture d'écran après la connexion et je suis bien français ;-)

![image](https://github.com/user-attachments/assets/3708374c-ad34-4957-bcb5-1dffb8f4942b)

**Comment by Jezza34000** [comment]
D'accord
Tu utilise la lib solo ou tu utilise via mon intégration de home assistant ?
Si c'est la première reponse donne moi ton le code qui execute cette erreur ?

**Comment by The-MasterChief** [comment]
J'utilise la librairie solo et je suis parti sur le code que tu donnes en exemple en y apportant quelques modifications pour comprendre le problème.

Voici le stdout de ton code sans aucune modification :

```
[...]
DEBUG:VeoliaAPI:Received response with status code 200
DEBUG:VeoliaAPI:Requesting access token...
DEBUG:VeoliaAPI:OK - Access token retrieved
DEBUG:VeoliaAPI:Getting user & billing data...
ERROR:root:An error occurred: call to= espace-client failed with http status= 403
DEBUG:VeoliaAPI:Closing session
```

Pour ma part, c'est l'appel à l'URL /espace-client?type-front=WEB_ORDINATEUR qui retourne un 403

**Comment by Jezza34000** [comment]
Ok il doit y avoir une spécificité que je n'ai jamais rencontré que ton compte a.
Il faudrait débugger ça, mais sans pouvoir reproduire l'erreur c'est compliqué de comprendre pourquoi l'appel à espace-client retourne le 403.
Tu sais comment utiliser l'inspecteur sous Chrome ? Car il faudrait ouvrir l'inspecteur sous Chrome, et en te connectant a ton compte normalement tu as un appel à https://prd-ael-sirius-backend.istefr.fr/espace-client?type-front=WEB_ORDINATEUR. 
Si c'est pas le cas c'est que il doit procéder autrement avec ton compte et dans ce cas si tu me donne le détail je pourrais adapter mon code.

**Comment by The-MasterChief** [comment]
As-tu une adresse email ou un discord pour discuter en privé tous les deux ?
Je pense que ce sera plus simple pour faire du debug ;-)

**Comment by Jezza34000** [comment]
jezza8837 discord

**Comment by The-MasterChief** [comment]
demande envoyée sur discord

**Comment by Jezza34000** [comment]
Après investigation il n'est pas possible de contacter l'API Veolia depuis des IP sources OVH

**Comment by The-MasterChief** [comment]
Après avoir fait des tests supplémentaires et installer un debian 12 + interface graphique, je confirme que je ne peux pas me connecter depuis un serveur OVH

Encore grand merci à @Jezza34000 pour son aide !!!
